# ===========================
# Training
# ===========================
checkpoint_path: './checkpoints/mnist'
max_checkpoints_to_keep: 200
max_num_images_kimg: 4000
checkpoint_intervall_kimg: 20
log_dir: './logs/mnist'
log_metrics_intervall_kimg: 1
dlatent_avg_beta: 0.95
print_metrics_intervall_kimg: 0.008
label_conditioning: True
shuffle_buffer_size: 50000
gamma: 100
disc_reg_intervall: 10

# ===========================
# Generation
# ===========================
truncation_psi: 0.5
truncation_cutoff: 200

# ===========================
# Inputs
# ===========================
num_channels: 1
resolution: 32
batch_size: 8
labels_size: 10

# ===========================
# Mapping Network
# ===========================
latent_size: 512
hidden_size: 512
dlatent_size: 512
num_dense_layers: 8
alpha: 0.2
lr_multiplier: 0.01
normalize_latents: True

# ===========================
# Synthesis Network
# ===========================

feature_maps_base: 8192
feature_maps_decay: 1.0
feature_maps_min: 1 
feature_maps_max: 512

# ===========================
# Discriminator
# ===========================

minibatch_std_group_size: 4
minibatch_std_n_features: 1

# ===========================
# Optimizer 
# ===========================
discriminator_base_learning_rate: 0.002
discriminator_beta_1: 0.0
discriminator_beta_2: 0.99
discriminator_epsilon: 1e-8
generator_base_learning_rate: 0.002
generator_beta_1: 0.0
generator_beta_2: 0.99
generator_epsilon: 1e-8